{{- define "main" }}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>🔐 Trivy Report</title>

<style>
body {
  font-family: "Segoe UI", Arial;
  background: #f4f6f8;
  margin: 0;
}

.header {
  background: #111827;
  color: white;
  padding: 20px 30px;
}

.container {
  padding: 25px;
}

.card {
  background: white;
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 25px;
  box-shadow: 0 8px 20px rgba(0,0,0,0.08);
}

h2 {
  margin-top: 0;
}

.section-title {
  margin-top: 20px;
  font-size: 16px;
  font-weight: bold;
  color: #374151;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 10px;
}

th {
  background: #1f2937;
  color: white;
  padding: 10px;
  text-align: left;
}

td {
  padding: 10px;
  border-bottom: 1px solid #e5e7eb;
}

tr:hover {
  background: #f9fafb;
}

.badge {
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: bold;
}

.CRITICAL { background: #fee2e2; color: #dc2626; }
.HIGH { background: #ffedd5; color: #ea580c; }
.MEDIUM { background: #fef9c3; color: #ca8a04; }
.LOW { background: #dcfce7; color: #16a34a; }

.empty {
  padding: 10px;
  background: #ecfdf5;
  border-radius: 8px;
  color: #065f46;
}

.footer {
  text-align: center;
  font-size: 12px;
  color: #6b7280;
  margin-top: 30px;
}
</style>

</head>

<body>

<div class="header">
  <h1>🔐 Trivy Security Report</h1>
</div>

<div class="container">

{{ range . }}
<div class="card">

<h2>📦 Target: {{ .Target }}</h2>
<p><b>Type:</b> {{ .Type }}</p>

<!-- ================= VULNERABILITIES ================= -->
<div class="section-title">🚨 Vulnerabilities</div>

{{ if .Vulnerabilities }}
<table>
<tr>
<th>Package</th>
<th>Severity</th>
<th>CVE</th>
<th>Installed</th>
<th>Fixed</th>
</tr>

{{ range .Vulnerabilities }}
<tr>
<td>{{ .PkgName }}</td>
<td><span class="badge {{ .Severity }}">{{ .Severity }}</span></td>
<td>{{ .VulnerabilityID }}</td>
<td>{{ .InstalledVersion }}</td>
<td>{{ .FixedVersion }}</td>
</tr>
{{ end }}

</table>
{{ else }}
<div class="empty">✅ No vulnerabilities found</div>
{{ end }}

<!-- ================= MISCONFIG ================= -->
<div class="section-title">⚙️ Misconfigurations</div>

{{ if .Misconfigurations }}
<table>
<tr>
<th>ID</th>
<th>Type</th>
<th>Severity</th>
<th>Message</th>
</tr>

{{ range .Misconfigurations }}
<tr>
<td>{{ .ID }}</td>
<td>{{ .Type }}</td>
<td><span class="badge {{ .Severity }}">{{ .Severity }}</span></td>
<td>{{ .Message }}</td>
</tr>
{{ end }}

</table>
{{ else }}
<div class="empty">✅ No misconfigurations found</div>
{{ end }}

</div>
{{ end }}

<div class="footer">
Generated by Trivy • Clean DevSecOps Report 🚀
</div>

</div>

</body>
</html>
{{- end }}
