{{- define "main" }}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>🔐 Trivy Report</title>

{{- if . }}

<style>
body {
  font-family: "Segoe UI", Arial;
  background: #f3f4f6;
  margin: 0;
}

.header {
  background: #111827;
  color: white;
  padding: 20px;
  text-align: center;
}

.container {
  padding: 20px;
}

.card {
  background: white;
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 25px;
  box-shadow: 0 6px 15px rgba(0,0,0,0.08);
}

h2 {
  margin: 0 0 10px 0;
}

.section {
  margin-top: 20px;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 10px;
}

th {
  background: #1f2937;
  color: white;
  padding: 10px;
}

td {
  padding: 10px;
  border-bottom: 1px solid #e5e7eb;
}

tr:hover {
  background: #f9fafb;
}

.badge {
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: bold;
}

.CRITICAL { background: #fee2e2; color: #dc2626; }
.HIGH { background: #ffedd5; color: #ea580c; }
.MEDIUM { background: #fef9c3; color: #ca8a04; }
.LOW { background: #dcfce7; color: #16a34a; }

.empty {
  padding: 12px;
  background: #ecfdf5;
  border-radius: 8px;
  color: #065f46;
  margin-top: 10px;
}

.footer {
  text-align: center;
  font-size: 12px;
  color: #6b7280;
  margin-top: 30px;
}
</style>

</head>

<body>

<div class="header">
  <h1>🔐 Trivy Security Report</h1>
  <p>{{ now }}</p>
</div>

<div class="container">

{{ range . }}
<div class="card">

<h2>📦 {{ escapeXML .Target }}</h2>
<p><b>Type:</b> {{ .Type }}</p>

<!-- ================= VULNERABILITIES ================= -->
<div class="section">
<h3>🚨 Vulnerabilities</h3>

{{- if (eq (len .Vulnerabilities) 0) }}
<div class="empty">✅ No HIGH/CRITICAL vulnerabilities found</div>
{{- else }}

<table>
<tr>
<th>Package</th>
<th>ID</th>
<th>Severity</th>
<th>Installed</th>
<th>Fixed</th>
</tr>

{{- range .Vulnerabilities }}
<tr>
<td>{{ escapeXML .PkgName }}</td>
<td>{{ escapeXML .VulnerabilityID }}</td>
<td><span class="badge {{ .Vulnerability.Severity }}">{{ .Vulnerability.Severity }}</span></td>
<td>{{ escapeXML .InstalledVersion }}</td>
<td>{{ escapeXML .FixedVersion }}</td>
</tr>
{{- end }}

</table>
{{- end }}
</div>

<!-- ================= MISCONFIG ================= -->
<div class="section">
<h3>⚙️ Misconfigurations</h3>

{{- if (eq (len .Misconfigurations) 0) }}
<div class="empty">✅ No misconfigurations found</div>
{{- else }}

<table>
<tr>
<th>ID</th>
<th>Type</th>
<th>Severity</th>
<th>Message</th>
</tr>

{{- range .Misconfigurations }}
<tr>
<td>{{ escapeXML .ID }}</td>
<td>{{ escapeXML .Type }}</td>
<td><span class="badge {{ .Severity }}">{{ .Severity }}</span></td>
<td>{{ escapeXML .Message }}</td>
</tr>
{{- end }}

</table>
{{- end }}

</div>

</div>
{{ end }}

<div class="footer">
Generated by Trivy • DevSecOps Ready 🚀
</div>

</div>

{{- else }}

</head>
<body>
<h1 style="text-align:center;">⚠️ No scan results (No HIGH/CRITICAL vulnerabilities)</h1>

{{- end }}

</body>
</html>
{{- end }}
