{{- define "main" }}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>🔐 Trivy Security Report</title>

<style>
body {
  font-family: "Segoe UI", Arial, sans-serif;
  margin: 0;
  background: #f3f4f6;
}

.header {
  background: linear-gradient(90deg, #111827, #1f2937);
  color: white;
  padding: 20px 30px;
}

.header h1 {
  margin: 0;
  font-size: 24px;
}

.container {
  padding: 20px 30px;
}

.card {
  background: white;
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 25px;
  box-shadow: 0 6px 18px rgba(0,0,0,0.08);
}

h2 {
  margin-top: 0;
  font-size: 20px;
}

.summary {
  margin: 10px 0 20px 0;
  font-size: 14px;
  color: #374151;
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
}

th {
  background: #111827;
  color: white;
  text-align: left;
  padding: 10px;
}

td {
  padding: 10px;
  border-bottom: 1px solid #e5e7eb;
}

tr:hover {
  background: #f9fafb;
}

.CRITICAL { color: #dc2626; font-weight: bold; }
.HIGH { color: #ea580c; font-weight: bold; }
.MEDIUM { color: #ca8a04; }
.LOW { color: #16a34a; }

.badge {
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: bold;
}

.CRITICAL.badge { background: #fee2e2; }
.HIGH.badge { background: #ffedd5; }
.MEDIUM.badge { background: #fef9c3; }
.LOW.badge { background: #dcfce7; }

.footer {
  text-align: center;
  font-size: 12px;
  color: #6b7280;
  margin-top: 30px;
}
</style>

</head>

<body>

<div class="header">
  <h1>🔐 Trivy Security Scan Report</h1>
</div>

<div class="container">

{{ range .Results }}
<div class="card">

<h2>📦 Target: {{ .Target }}</h2>

<div class="summary">
  Type: {{ .Type }} <br>
  Total Vulnerabilities: {{ len .Vulnerabilities }}
</div>

{{ if .Vulnerabilities }}

<table>
<tr>
<th>Package</th>
<th>Severity</th>
<th>CVE</th>
<th>Installed</th>
<th>Fixed</th>
</tr>

{{ range .Vulnerabilities }}
<tr>
<td>{{ .PkgName }}</td>
<td>
  <span class="badge {{ .Severity }}">{{ .Severity }}</span>
</td>
<td>{{ .VulnerabilityID }}</td>
<td>{{ .InstalledVersion }}</td>
<td>{{ .FixedVersion }}</td>
</tr>
{{ end }}

</table>

{{ else }}
<p>✅ No vulnerabilities found</p>
{{ end }}

</div>
{{ end }}

<div class="footer">
  Generated by Trivy • Secure your containers 🚀
</div>

</div>

</body>
</html>
{{- end }}
